parent_cfg: "configs/inb/inb_377.yaml"

train_dataset:
  data_root: "data/zju-mocap/my_393"
  human: "my_393"
  ann_file: "data/zju-mocap/my_393/annots.npy"

val_dataset:
  data_root: "data/zju-mocap/my_393"
  human: "my_393"
  ann_file: "data/zju-mocap/my_393/annots.npy"

test_dataset:
  data_root: "data/zju-mocap/my_393"
  human: "my_393"
  ann_file: "data/zju-mocap/my_393/annots.npy"

bullet:
  dataset_kwargs:
    data_root: "data/zju-mocap/my_393"
    ann_file: "data/zju-mocap/my_393/annots.npy"
    human: "my_393"

# data options
training_view: [0,6,12,18]
test_view: [1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 19, 20, 21, 22]
begin_ith_frame: 0
num_train_frame: 300
frame_interval: 1

test:
  frame_sampler_interval: 6

smpl_thresh: 0.05
exp_name: inb_393
pair_loss_weight: 10.0

smpl_meta : "data/zju-mocap/my_393/smpl_lbs"